"""Generates the actual/gap-filled/predicted chain figures for every model in the B-10/B-13
recursive-rollout sequence, reading directly from `results/b10_b13_full_chains.csv` (the
consolidated raw-prediction export, D-65 addendum).

This is a **committed** replacement for a process that was previously always ad-hoc and lost: the
existing `results/figures/b10_chains/` figures (RF/XGB/LightGBM/SARIMAX/2 ensembles/DLinear/LSTM/
TabPFN -- 9 of the 11 models now in `b10_b13_full_chains.csv`, each with full 3-tower x 5-anchor
coverage) were generated by uncommitted, since-lost scripts (confirmed via repo-wide search while
researching the DLinear/LSTM model-roster extension, D-65 3rd addendum) -- the same "ad-hoc, not
committed" pattern this project has repeatedly had to retroactively fix (B-10/B-13's own
multi-anchor scripts, D-65). **TFT is the one genuine coverage gap** -- only 1 of 15 combinations
(`T4_anchor2021_TFT.png`) exists. TabICLv2 (D-66) never had any figures at all until this script.
Going forward (per direct user request): **forecasting work should always generate these figures
and keep `b10_b13_full_chains.csv` current** -- this script is the reusable, rerunnable way to do
that, rather than another one-off.

Regenerating the 8 already-figured models from `b10_b13_full_chains.csv` is expected to reproduce
the existing PNGs almost exactly for every deterministic model (RF/XGB/LightGBM/SARIMAX/both
ensembles/LSTM) -- already verified bit-for-bit consistent with the archived figures earlier this
session (RF/LSTM/DLinear at Tower 4/anchor 2021 matched pixel-for-pixel; DLinear's 2018 anchor did
not, due to its already-documented non-determinism, D-65 3rd addendum). TFT will differ from any
prior informal look at it (never systematically archived, and independently non-deterministic,
D-62 addendum) -- expected, not a bug.
"""
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

ROOT = r"c:\Users\Nicholas\Documents\COMP0191 MSc Artificial Intelligence for Sustainable Development Project"
RESULTS = rf"{ROOT}\results"
FIG_DIR = Path(RESULTS) / "figures" / "b10_chains"
FIG_DIR.mkdir(parents=True, exist_ok=True)

MODEL_COLORS = {
    "RF": "tab:green", "XGB": "tab:orange", "LightGBM": "tab:blue", "SARIMAX": "tab:red",
    "Ensemble_unweighted": "tab:purple", "Ensemble_MASEweighted": "tab:pink",
    "TFT": "tab:brown", "TabPFN": "tab:cyan",
    "DLinear": "tab:olive", "LSTM": "orchid", "TabICLv2": "teal",
    # S-03 driver-availability ablation (D-70): variant-suffixed model columns merged into
    # b10_b13_full_chains.csv -- reuse each base model's own hue, distinguished by line style
    # is not available here (plot_chain draws one color per call), so a lighter/muted tint per
    # variant keeps them visually distinct from Model 1's own full-feature chains above.
    "RF_S03_A_removal": "yellowgreen", "RF_S03_B_resample": "darkgreen",
    "XGB_S03_A_removal": "navajowhite", "XGB_S03_B_resample": "darkorange",
    "LightGBM_S03_A_removal": "lightskyblue", "LightGBM_S03_B_resample": "navy",
    "SARIMAX_S03_A_removal": "lightcoral", "SARIMAX_S03_B_resample": "darkred",
    "Ensemble_unweighted_S03_A_removal": "plum", "Ensemble_unweighted_S03_B_resample": "indigo",
    "Ensemble_MASEweighted_S03_A_removal": "lightpink", "Ensemble_MASEweighted_S03_B_resample": "deeppink",
    # S-03 model-roster extension (D-70 follow-up): TFT/TabPFN/DLinear/LSTM/TabICLv2 variants,
    # same muted-tint-per-variant convention as the tree/ensemble models above.
    "TFT_S03_A_removal": "burlywood", "TFT_S03_B_resample": "saddlebrown",
    "TabPFN_S03_A_removal": "paleturquoise", "TabPFN_S03_B_resample": "darkcyan",
    "DLinear_S03_A_removal": "khaki", "DLinear_S03_B_resample": "darkolivegreen",
    "LSTM_S03_A_removal": "violet", "LSTM_S03_B_resample": "purple",
    "TabICLv2_S03_A_removal": "lightseagreen", "TabICLv2_S03_B_resample": "darkslategray",
    # Gap-filled-target/-context ablation (D-7x): DLinear/LSTM/TFT trained on y_gapfilled instead of
    # masked y_observed; TabPFN/TabICLv2 given y_gapfilled as context instead of y_observed. Muted
    # tint per model, same convention as the S-03 variants above.
    "DLinear_gf": "darkkhaki", "LSTM_gf": "mediumorchid", "TFT_gf": "peru",
    "TabPFN_gf": "darkturquoise", "TabICLv2_gf": "seagreen",
}


def plot_chain(sub, tower, yr, model):
    fig, ax = plt.subplots(figsize=(13, 5))
    ax.plot(sub.date, sub.y_gapfilled, ":", color="gray", linewidth=1, label="Gap-filled FCH4")
    base_model = model.split("_S03_")[0].split("_gf")[0]
    y_true_col = "y_true_tft" if base_model in ("TFT", "DLinear", "LSTM") else "y_true"
    ax.plot(sub.date, sub[y_true_col], "-", color="black", linewidth=1, label="Actual FCH4 (observed)")
    color = MODEL_COLORS.get(model, "tab:gray")
    ax.plot(sub.date, sub[model], "-", color=color, linewidth=1.2, label=f"{model} (predicted)")
    ax.set_title(f"Tower {tower}, anchor {yr}-12-16, model={model}")
    ax.set_ylabel("FCH4 (nmol m-2 s-1)")
    ax.legend(loc="upper right", fontsize=8)
    fig.tight_layout()
    fig.savefig(FIG_DIR / f"T{tower}_anchor{yr}_{model}.png", dpi=100)
    plt.close(fig)


def main():
    chains = pd.read_csv(f"{RESULTS}/b10_b13_full_chains.csv", parse_dates=["date"])
    models = [c for c in chains.columns
              if c not in ("date", "tower", "anchor_year", "y_true", "y_true_tft", "y_gapfilled", "persistence")]
    print(f"Models found: {models}")

    n_saved = 0
    for (tower, yr), sub in chains.groupby(["tower", "anchor_year"]):
        sub = sub.sort_values("date")
        for model in models:
            if sub[model].notna().any():
                plot_chain(sub, tower, yr, model)
                n_saved += 1

    print(f"[OK] Saved {n_saved} figures to {FIG_DIR}")


if __name__ == "__main__":
    main()
